### ISSUE TITLE
国外下载镜像

### ISSUE THREAD

**Issue by Naozumi520** [kingo132/quark-n-openwrt#1]
我住在香港，不能用百度云. 请问你能上传到其他地方吗, 谢谢.

**Comment by kingo132** [comment]
你好，我更新了谷歌分享，你可以尝试这个链接：
https://drive.google.com/file/d/1VpMPoZBd1CTCEauSvclEKeQTPj9Nv3Ge/view?usp=sharing

**Comment by Naozumi520** [comment]
謝謝回复. 我可以下載了，感謝!
